### ISSUE TITLE
Try to run the samples

### ISSUE THREAD

**Issue by lisbuenas** [aminerol/react-query-firestore#1]
I'm current using the React v16.8 and just copied and pasted the query

 const { data } = useCollection('users', {}, {
    where: ['name', '==', 'fernando'],
    limit: 10,
    orderBy: ['age', 'desc'],
  })

And seems that there's a missing type
Type '"name"' is not assignable to type '"id" | "exists" | "hasPendingWrites" | FieldPath | KeyHack

**Comment by aminerol** [comment]
Thanks for reporting this, its fixed now on [v0.1.2](https://github.com/aminerol/react-query-firestore/releases/tag/v0.1.2)
