### ISSUE TITLE
Not Working with Firebase V9

### ISSUE THREAD

**Issue by AtticusCMBM** [aminerol/react-query-firestore#6]
Hello.  when I try to pass in my data base to the firestore prop in  
```
<ReactQueryFirestoreProvider
      firestore={db}
      reactQueryConfig={reactQueryConfig}
    >
```
I am getting 

> TypeError: firestore.collection is not a function
    at createFirestoreRef

In my mounted component  I am simply calling 

``const { data, add, error } = useCollection(`trainings`);``

Any Idea how to fix this as I would love to use the library? I don't want to have to downgrade completely to firebase V8.

Thank you so much

**Comment by aminerol** [comment]
unfortunately i only support firebase v8, and am having no intention to support v9 at least for now.
you might wanna check [react-query-firebase](https://react-query-firebase.invertase.dev/) they do support v9
