### ISSUE TITLE
parseDates erroring on null values

### ISSUE THREAD

**Issue by hirvesh** [aminerol/react-query-firestore#9]
When reading data using useDocument, parseDate function is crashing. On investigation it seems like this line: https://github.com/aminerol/react-query-firestore/blob/ee408474d2e207560b7f3075d9803acb12655d2d/src/utils.ts#L7 is not included in release 0.3.1.

Can we have a version 0.3.2 with this please @aminerol :)

**Comment by acarmody86** [comment]
Just sent an email, would love the fix asap please @aminerol. Great work!

**Comment by aminerol** [comment]
Hey @hirvesh  @acarmody86 , i just did release 0.3.2 to npm. Thank you
